name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      MQTT_SERVER: 127.0.0.1
    steps:
    - uses: actions/checkout@v4
      with:
         submodules: "recursive"
    - name: Build
      run: cargo build --all
    - name: Examples
      run: cargo build --all --examples

    - name: Start Mosquitto
      uses: namoshek/mosquitto-github-action@v1
      with:
        ports: '1883:1883'
        config: ${{ github.workspace }}/mosquitto-rs/mosquitto.conf
    - name: Run tests
      run: cargo test --all -- --show-output
    - name: Check formatting
      run: cargo fmt --all -- --check


  system-libs:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo -n apt-get update
        sudo -n apt-get install -y libmosquitto-dev
    - name: Build
      run: cd mosquitto-rs && cargo build --no-default-features
    - name: Examples
      run: cd mosquitto-rs && cargo build --no-default-features --examples
    - name: Run tests
      run: cd mosquitto-rs && cargo test --no-default-features
  mac:
    strategy:
      fail-fast: false
    runs-on: "macos-latest"
    steps:
    - uses: actions/checkout@v4
      with:
         submodules: "recursive"
    - name: Build
      run: cargo build -p mosquitto-rs --all-features
    - name: Examples
      run: cargo build -p mosquitto-rs --all-features --examples
    - name: Run tests
      run: cargo test -p mosquitto-rs --all-features
  windows:
    strategy:
      fail-fast: false
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v4
      with:
         submodules: "recursive"
    - name: Build
      run: cargo build -p mosquitto-rs --all-features
    - name: Examples
      run: cargo build -p mosquitto-rs --all-features --examples
    - name: Run tests
      run: cargo test -p mosquitto-rs --all-features
